name: casper-a100-label
run-name: ${{ github.actor }} compiling and running CUDA hello world example
on:
  pull_request:
    types:
      - labeled

jobs:
  
  build-and-run:
    runs-on: basic-runner
    if: |
      github.event.label.name == 'casper-a100' &&
      github.repository == 'neumanbrett/cuda_ghactions_basic'

    env:
      USER: bneuman
      PBS_ACCOUNT: SCSG0001

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3

      - name: Source system variables based on label
        run: |
          source config/config.modules
          source config/config.pbs

      - name: Run make
        run: make > make.log 2>&1
          
      - name: Verify compilation
        run: |
          if [ ! -f bin/hello_world ]; then
            echo "Compilation failed: binary not found"
            exit 1
          fi
          if [ ! -s make.log ]; then
            echo "Compilation failed: make.log is empty"
            exit 1
          fi
          if ! tail -n 1 make.log | grep -q "Success"; then
            echo "Compilation failed: make.log does not end with 'Success'"
            exit 1
          fi
          cat make.log > $SCRATCH/tmp/make.log.$(date +"%d-%m-%Y")
          rm make.log

      - name: Submit PBS job to run executable
        #run: JOBID = $(qsub -A $PBS_ACCOUNT -l select=1:ncpus=1:ngpus=1:mem=10GB:gpu_model=a100 -l walltime=00:05:00 -N hello_world -o hello_world.out -e hello_world.err bin/hello_world)
        run: |
          echo $USER
          qsub -Wblock=true validate/run-validate.pbs

      - name: Verify run
        run: |
          if [ ! -f validate/validate_job.log ]; then
            echo "Run failed: validate_job.log not found"
            exit 1
          fi
          if ! grep -q "CPU" validate/validate_job.log; then
            echo "The job did not run on the CPU"
            exit 1
          fi
          if ! grep -q "GPU" validate/validate_job.log; then
            echo "The job did not run on the GPU"
            exit 1
          fi
          cat validate/validate_job.log > $SCRATCH/tmp/validate_job.log.$(date +"%d-%m-%Y") 
          rm validate/validate_job.log 