name: Casper Build and Test CUDA Hello World
run-name: ${{ github.actor }} compiling and running CUDA hello world example for Casper
on:
  workflow_call:

jobs:

  casper-a100-workflow:
    if: |
      github.event.label.name == casper ||
      github.event.label.name == casper-a100

    name: Running workflow on Casper A100
    uses: ./.github/workflows/casper-a100.yml
  
  casper-v100-workflow:
    if: |
      github.event.label.name == casper ||
      github.event.label.name == casper-v100

    name: Running workflow on Casper V100
    uses: ./.github/workflows/casper-v100.yml