name: Casper V100 Test
run-name: ${{ github.actor }} runtime test for CUDA code on Casper V100
on:
  workflow_call:

jobs:
  
  test:
    runs-on: basic-runner
    
    env:
      WORKFLOW_PBS_JOBSCRIPT: validate/run-validate.sh

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
      
      # This step will check that the PBS job ran successfully (return code 0)
      - name: Submit PBS job
        run: qsub -Wblock=true ${{ env.WORKFLOW_PBS_JOBSCRIPT }}

      - name: Verifying output
        run: echo "PBS job ran successfully"