name: Derecho Build and Test CUDA Hello World
run-name: ${{ github.actor }} compiling and running CUDA hello world example for Casper
on:
  workflow_call:

jobs:

  derecho-build:

    name: Building on Derecho
    uses: ./.github/workflows/derecho-build.yml

  derecho-test:
  
      name: Testing on Derecho
      # Waits for the build job to complete before running
      needs: derecho-build
      uses: ./.github/workflows/derecho-test.yml