name: NCAR Systems Build and Test CUDA Hello World
run-name: ${{ github.actor }} compiling and running CUDA hello world example
on:
  pull_request:
    types:
      - labeled

env:
  WORKFLOW_REPOSITORY: neumanbrett/cuda_ghactions_basic
  WORKFLOW_RUNNER: basic-runner

jobs:

  casper-workflow:
    runs-on: ${{ env.WORKFLOW_RUNNER }}
    strategy:
      matrix:
        label: [casper, casper-a100, casper-v100]

    if: |
      github.repository == ${{ env.WORKFLOW_REPOSITORY }} &&
      github.event.label.name == matrix.label

    name: Running on Casper
    uses: ./.github/workflows/casper.yml

  derecho-workflow:
    runs-on: ${{ env.WORKFLOW_RUNNER }}
    strategy:
      matrix:
        label: [derecho]

    if: |
      github.repository == ${{ env.WORKFLOW_REPOSITORY }} &&
      github.event.label.name == matrix.label

    name: Running on Derecho
    # Require the build job to complete before running
    uses: ./.github/workflows/derecho.yml
